#=================================================
# Description: Build OpenWrt using GitHub Actions
# Lisence: MIT
# Author: eSirPlayground
# Youtube Channel: https://goo.gl/fvkdwm
#=================================================

name: Build_360_T7_108M_ubi

on:
  # Add a button to trigger the workflow
  repository_dispatch:
  workflow_dispatch:

  # release:
  #   types: [published]

  #push:
  #  branches:
  #    - master

  # schedule:
  #   - cron: 0 21 * * 5

  #watch:
  #  types: [started]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        set +e
        docker rmi `docker images -q`
        echo "Deleting files, please wait ..."
        sudo rm -rf \
          /usr/share/dotnet \
          /usr/local/lib/android \
          /opt/ghc \
          /etc/mysql \
          /etc/php
        sudo -E apt-get -y purge azure-cli* docker* ghc* zulu* hhvm* llvm* firefox* google* dotnet* aspnetcore* powershell* openjdk* adoptopenjdk* mysql* php* mongodb* moby* snap* || true
        sudo -E apt-get clean
        sudo -E apt-get update -y
        sudo -E apt full-upgrade -y
        sudo -E apt install -y ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential \
          bzip2 ccache clang clangd cmake cpio curl device-tree-compiler ecj fastjar flex gawk gettext gcc-multilib \
          g++-multilib git gperf haveged help2man intltool lib32gcc-s1 libc6-dev-i386 libelf-dev libglib2.0-dev \
          libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses5-dev libncursesw5 libncursesw5-dev libreadline-dev \
          libssl-dev libtool lld lldb lrzsz mkisofs msmtp nano ninja-build p7zip p7zip-full patch pkgconf python2.7 \
          python3 python3-pip python3-ply python-docutils qemu-utils re2c rsync scons squashfs-tools subversion swig \
          texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev
        sudo -E apt-get -y autoremove --purge
        sudo -E apt-get clean

    - name: Check Space
      run: |
        df -h

    - name: Clone source code
      env:
        REPO_URL: https://github.com/hanwckf/immortalwrt-mt798x
        REPO_BRANCH: openwrt-21.02
      run: |
        git clone --depth 1 $REPO_URL -b $REPO_BRANCH openwrt
    #    cd openwrt
    #    echo "src-git helloworld https://github.com/fw876/helloworld.git" >> ./feeds.conf.default
    #    echo "src-git passwall https://github.com/xiaorouji/openwrt-passwall.git" >> ./feeds.conf.default

    #- name: Cache
    #  uses: klever1988/cachewrtbuild@main
    #  with:
    #    ccache: 'true'
    #    prefix: ./openwrt

    - name: Update & Install feeds
      working-directory: ./openwrt
      run: |
        sed -i '1i src-git xiaorouji https://github.com/xiaorouji/openwrt-passwall-packages' feeds.conf.default
        sed -i '2i src-git passwall2 https://github.com/xiaorouji/openwrt-passwall2' feeds.conf.default
        ./scripts/feeds update -a
        rm -rfv ./feeds/packages/net/{xray*,v2ray-*}
        git clone -b master --single-branch https://github.com/immortalwrt/packages.git packages_master
        mv -v ./packages_master/lang/rust ./feeds/packages/lang
        rm -rfv ./feeds/packages/lang/golang
        mv -v ./packages_master/lang/golang ./feeds/packages/lang
        rm -rfv ./packages_master
        git clone https://github.com/kenzok8/small.git
        rm -rfv ./feeds/xiaorouji/shadowsocks-rust
        mv -v ./small/shadowsocks-rust ./feeds/xiaorouji
        #rm -rfv ./feeds/xiaorouji/naiveproxy
        #mv -v ./small/naiveproxy ./feeds/xiaorouji
        rm -rfv ./small
        ./scripts/feeds install -a
        ./scripts/feeds install -a

    - name: Import external feeds - luci-app-adguardhome
      working-directory: ./openwrt
      run: |
        git clone https://github.com/tty228/luci-app-adguardhome.git package/luci-app-adguardhome

    #- name: Import external feeds - luci-app-passwall2
    #  working-directory: ./openwrt
    #  run: |
    #    rm -rf feeds/luci/applications/luci-app-passwall
    #    git clone https://github.com/xiaorouji/openwrt-passwall2.git package/luci-app-passwall2
    #    git clone https://github.com/xiaorouji/openwrt-passwall-packages.git package/luci-app-passwall-packages

    - name: Configuration Customization - Build_360_T7_108M_ubi
      env:
        CONFIG_FILE: '360_T7_108M_ubi_mtwifi_cfg.config'
      run: |
        [ -e $CONFIG_FILE ] && mv -f $CONFIG_FILE openwrt/.config
        chmod +x ./my_customize_360_T7.sh && ./my_customize_360_T7.sh
        cd openwrt && make defconfig

    - name: Download package
      working-directory: ./openwrt
      run: |
        make download -j$(nproc)
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;

    - name: Check Space
      run: |
        df -h

    - name: Build firmware
      working-directory: ./openwrt
      run: |
        echo -e "$(nproc) thread build."
        make -j$(nproc) V=s
        #make -j1 V=s

    - name : Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: OpenWrt
        path: openwrt/bin
