#=================================================
# Description: Build OpenWrt using GitHub Actions
# Lisence: MIT
# Author: eSirPlayground
# Youtube Channel: https://goo.gl/fvkdwm
#=================================================

name: Build_360_T7_2410_6.6

on:
  # Add a button to trigger the workflow
  repository_dispatch:
  workflow_dispatch:
  
  schedule:
    - cron: 0 0 28 * *
  
jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        set +e
        docker rmi `docker images -q`
        echo "Deleting files, please wait ..."
        sudo rm -rf \
          /usr/share/dotnet \
          /usr/local/lib/android \
          /opt/ghc \
          /etc/mysql \
          /etc/php
        sudo -E apt-get -y purge azure-cli* docker* ghc* zulu* hhvm* llvm* firefox* google* dotnet* aspnetcore* powershell* openjdk* adoptopenjdk* mysql* php* mongodb* moby* snap* || true
        sudo -E apt-get clean
        sudo -E apt-get update -y
        sudo -E apt full-upgrade -y
        sudo bash -c 'bash <(curl -s https://build-scripts.immortalwrt.org/init_build_environment.sh)'
        sudo -E apt-get -y autoremove --purge
        sudo -E apt-get clean

    - name: Check Space
      run: |
        df -h

    - name: Clone source code
      env:
        REPO_URL: https://github.com/padavanonly/immortalwrt-mt798x-6.6
        REPO_BRANCH: openwrt-24.10-6.6
      run: |
        git clone -b $REPO_BRANCH --single-branch --filter=blob:none $REPO_URL openwrt

    - name: Update & Install feeds
      working-directory: ./openwrt
      run: |
        ./scripts/feeds update -a
        rm -rf feeds/packages/net/zerotier
        ./scripts/feeds install -a
        ./scripts/feeds install -af

    - name: Build New Version For Zerotier
      working-directory: ./openwrt
      run: |
        sed -i 's/+zerotier/+luci-base/g' feeds/luci/applications/luci-app-zerotier/Makefile
        git clone https://github.com/mwarning/zerotier-openwrt.git package/zerotier-openwrt

    - name: Import external feeds - luci-app-nikki
      working-directory: ./openwrt
      run: |
        git clone -b main --single-branch --filter=blob:none https://github.com/nikkinikki-org/OpenWrt-nikki.git package/OpenWrt-nikki
        rm -rf package/OpenWrt-nikki/mihomo-alpha
        sed -i 's/[[:space:]]\++mihomo[[:space:]]*//' package/OpenWrt-nikki/nikki/Makefile

    - name: Import external feeds - luci-app-adguardhome
      working-directory: ./openwrt
      run: |
        git clone https://github.com/w9315273/luci-app-adguardhome.git package/luci-app-adguardhome

    - name: Configuration Customization - Build_360_T7_2410_6.6
      env:
        CONFIG_FILE: '360_T7_2410_6.6.config'
      run: |
        [ -e $CONFIG_FILE ] && mv -f $CONFIG_FILE openwrt/.config
        chmod +x ./my_customize_360_T7_2410.sh && ./my_customize_360_T7_2410.sh
        cd openwrt && make defconfig

    - name: Download package
      working-directory: ./openwrt
      run: |
        make download -j$(nproc)
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;

    - name: Check Space
      run: |
        df -h

    - name: Build firmware
      working-directory: ./openwrt
      run: |
        echo -e "$(nproc) thread build."
        make -j$(nproc) V=s
        #make -j1 V=s

    - name: Get date
      run: |
        echo "BUILD_DATE=$(TZ='Asia/Shanghai' date +'%Y%m%d')" >> $GITHUB_ENV

    - name : Upload artifact
      uses: actions/upload-artifact@v6
      with:
        name: OpenWrt-24.10with6.6-${{ env.BUILD_DATE }}
        path: openwrt/bin
